server:
  port: 8082
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: admin_user_2
    password: secure_password_2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.shop.paymentservice.event.OrderCreatedEvent
        spring.json.trusted.packages: "com.shop.*"

