server:
  port: 8083
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_db
    username: admin_user_3
    password: secure_password_3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.shop.inventoryservice.event.OrderCreatedEvent
        spring.json.trusted.packages: "com.shop.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer